"""with_travel_pro

Revision ID: 54922189cbdf
Revises: 012b4bcf0fb6
Create Date: 2026-06-01 15:58:27.551500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54922189cbdf'
down_revision: Union[str, None] = '012b4bcf0fb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Set with_travel_pro to True for existing campaigns
    op.add_column('campaign', sa.Column(
        'with_travel_pro', sa.Boolean(), nullable=False, server_default=sa.sql.expression.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign', 'with_travel_pro')
    # ### end Alembic commands ###
