"""reward_documents

Revision ID: ed1e707a57d1
Revises: 54922189cbdf
Create Date: 2026-06-02 09:51:24.785381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ed1e707a57d1'
down_revision: Union[str, None] = '54922189cbdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rewarddocument',
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('content', sa.LargeBinary(), nullable=True),
                    sa.Column('size', sa.Integer(), nullable=True),
                    sa.Column(
                        'token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('campaign_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['campaign_id'], ['campaign.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('token')
                    )
    op.create_index(op.f('ix_rewarddocument_id'),
                    'rewarddocument', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rewarddocument_id'), table_name='rewarddocument')
    op.drop_table('rewarddocument')
    # ### end Alembic commands ###
