"""willing_to_change

Revision ID: fcc3ae6b807c
Revises: ed1e707a57d1
Create Date: 2026-06-03 11:11:06.303389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcc3ae6b807c'
down_revision: Union[str, None] = 'ed1e707a57d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('change_required', sa.Boolean(
    ), nullable=False, server_default=sa.sql.expression.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign', 'change_required')
    # ### end Alembic commands ###
